FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json in the container
COPY package* ./

# Install the dependencies
RUN npm install

# Copy the entire project
COPY . ./

